name: Release APK

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Upload APK binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: releases/**/*.apk
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Upload AAB binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/**/*.aab
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
